# vim:ft=kitty

## name: Light
## reference: ~/.scripts/my-ghostty light mode

foreground                      #111111
background                      #ffffff
selection_foreground            #111111
selection_background            #cfe8ff

cursor                          #111111
cursor_text_color               #ffffff

# black
color0                          #000000
color8                          #808080

# red
color1                          #cc0000
color9                          #ff3333

# green
color2                          #008700
color10                         #00aa00

# yellow
color3                          #b58900
color11                         #cc9900

# blue
color4                          #0066cc
color12                         #3385ff

# magenta
color5                          #aa33aa
color13                         #cc33cc

# cyan
color6                          #008b8b
color14                         #00aaaa

# white
color7                          #d9d9d9
color15                         #ffffff
