#!/usr/bin/env bash

wid=$1
class=$2
title="$(xdotool getwindowname "$wid")"

Xaxis=$(xrandr --current | awk '/ connected /{getline; print $1}' | cut -dx -f1)
Yaxis=$(xrandr --current | awk '/ connected /{getline; print $1}' | cut -dx -f2)

center() {
  ((X = (Xaxis - $1) / 2))
  ((Y = (Yaxis - $2) / 2))
  echo "$1x$2+$X+$Y"
}
top_center() {
  ((X = (Xaxis - $1) / 2))
  echo "$1x$2+$X+10"
}
bottom_right() {
  ((X = Xaxis - $1))
  ((Y = Yaxis - $2))
  echo "$1x$2+$X+$Y"
}

is_dialog=$(xprop -id "$wid" | grep WINDOW_TYPE | grep DIALOG)
is_popup=$(xprop -id "$wid" | grep -i role | grep -i popup)

case "$title" in
"Event Tester")
  echo "state=floating"
  exit 0
  ;;
"Google Chrome")
  echo "state=floating"
  exit 0
  ;;
"meet.google.com is sharing your screen.")
  echo "hidden=on"
  exit 0
  ;;
"Firefox — Sharing Indicator")
  echo "hidden=on"
  exit 0
  ;;
"MangaReader")
  echo "state=floating"
  exit 0
  ;;
"LearnOpenGL")
  echo "state=floating"
  exit 0
  ;;
esac

[ -n "$is_dialog" ] && {
  echo "state=floating"
  exit 0
}

case "$class" in
Pavucontrol | pavucontrol)
  echo "state=floating focus=on rectangle=$(center 900 550)"
  exit 0
  ;;
Emacs | emacs)
  echo "desktop=5 focus=on follow=on"
  exit 0
  ;;
Google-chrome | Navigator)
  echo "desktop=3 focus=on follow=on state=tiling"
  exit 0
  ;;
firefox)
  [ -n "$is_popup" ] && {
    echo "focus=on follow=on"
    exit 0
  }
  echo "desktop=3 focus=on follow=on state=tiling"
  exit 0
  ;;
Zathura)
  echo "focus=on follow=on state=floating"
  exit 0
  ;;
zoom)
  case "$title" in
  "Meeting Chat")
    echo "state=floating focus=on follow=on rectangle=$(bottom_right 400 800)"
    exit 0
    ;;
  esac
  echo "desktop=9 focus=on follow=on"
  exit 0
  ;;
TopTracker)
  case "$title" in
  "New Activity Description" | "Current Activity Description")
    echo "state=floating rectangle=$(top_center 500 100)"
    exit 0
    ;;
  "Frame")
    echo "state=floating"
    exit 0
    ;;
  esac
  echo "desktop=8 state=floating focus=on rectangle=$(center 430 600)"
  exit 0
  ;;
Steam)
  case "$title" in
  "Friends List")
    echo "desktop=5 state=floating rectangle=$(bottom_right 300 700)"
    exit 0
    ;;
  "Steam")
    echo "desktop=5 state=tiling"
    exit 0
    ;;
  esac
  echo "desktop=5"
  exit 0
  ;;
Postman)
  echo "desktop=5"
  exit 0
  ;;
Slack | slack)
  echo "desktop=7 follow=on"
  exit 0
  ;;
deadcells)
  echo "desktop=9 state=floating"
  exit 0
  ;;
inlyne)
  echo "desktop=5"
  exit 0
  ;;
transmission-gtk | Transmission-gtk)
  echo "desktop=5"
  exit 0
  ;;
Evince | sioyek | obsidian | Soffice)
  echo "desktop=7"
  exit 0
  ;;
music-visualizer)
  echo "desktop=1 state=floating rectangle=$(top_center 500 100)"
  exit 0
  ;;
"Music Visualizer" | timer-gui)
  echo "desktop=1 state=floating"
  exit 0
  ;;
feh | simplescreenrecorder | SimpleScreenRecorder)
  echo "state=floating"
  exit 0
  ;;
deus)
  echo "desktop=5 state=floating"
  exit 0
  ;;
com.ghostty.tiso | ghostty)
  echo "border=on rectangle=0x0+0+0"
  exit 0
  ;;
passlock)
  echo "state=floating"
  exit 0
  ;;
esac
