#!/usr/bin/env bash

interval=${1:-1}
i=0;
while true; do
    xdotool key XF86MonBrightnessUp
    if [[ $((i%10)) == 0 ]]; then
        clear
        printf "INTERVAL: $interval \n\n"
    fi

    date

    sleep ${1:-1}
    i=$((i + 1))
done
