#!/bin/env python3
import json
import fileinput

stdin = "".join(fileinput.input())
try:
    s = json.loads(stdin)
    print(json.dumps(s, indent=4, sort_keys=True))
except json.decoder.JSONDecodeError:
    print(stdin[:-1])
