#!/bin/sh

# Let each terminal theme map these semantic ANSI colors appropriately.
DIR_COLOR="bold blue"
GIT_COLOR="green"
ACCENT_COLOR="red"

# Ensure config directory exists
mkdir -p ~/.config

# Generate and write config
cat > ~/.config/starship.toml << EOF
# colors: https://i.stack.imgur.com/KTSQa.png
# New line at the start of the prompt
add_newline = true

format = """
\$username\\
\$hostname\\
\$shlvl\\
\$kubernetes\\
\$directory\\
\$git_branch\\
\$git_commit\\
\$git_state\\
\$git_status\\
\$hg_branch\\
\$package\\
\$cmake\\
\$dart\\
\$dotnet\\
\$elixir\\
\$elm\\
\$erlang\\
\$golang\\
\$helm\\
\$java\\
\$julia\\
\$nim\\
\$nodejs\\
\$ocaml\\
\$perl\\
\$php\\
\$purescript\\
\$ruby\\
\$rust\\
\$python\\
\$swift\\
\$terraform\\
\$zig\\
\$nix_shell\\
\$conda\\
\$memory_usage\\
\$aws\\
\$gcloud\\
\$openstack\\
\$env_var\\
\$crystal\\
\$cmd_duration\\
\$custom\\
\$line_break\\
\$lua\\
\$jobs\\
\$battery\\
\$time\\
\$status\\
\$character"""

[aws]
disabled = true

[battery]
disabled = true

[cmd_duration]
min_time = 10_000

[conda]
symbol = " "

[dart]
symbol = " "
disabled = true

[directory]
read_only = " 🔒"
read_only_style = "red"
truncate_to_repo = true
truncation_length = 20
style = "$DIR_COLOR"
format = "[\$path](\$style) "

[elixir]
symbol = " "

[elm]
symbol = " "

[gcloud]
disabled = true

[git_branch]
symbol = " "
style = "$GIT_COLOR"
format = "[\$symbol\$branch](\$style) "

[git_status]
style = "$ACCENT_COLOR"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "
disabled = true

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "
EOF

echo "Starship config updated"
