#!/usr/bin/env bash

npm i -D \
	@typescript-eslint/eslint-plugin \
	@typescript-eslint/parser \
	eslint \
	eslint-config-airbnb-base \
	eslint-config-airbnb-typescript \
	prettier-airbnb-config \
	typescript \
	@types/node \
	ts-node \
	ts-node-dev \
	@tsconfig/node16

mkdir src 2>/dev/null

cat <<EOF >>.eslintrc.cjs
module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es2021: true,
  },
  extends: ['airbnb-base', 'airbnb-typescript/base', 'eslint:recommended', 'plugin:@typescript-eslint/recommended'],
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 12,
  },
  plugins: ['@typescript-eslint'],
  rules: {},
};
EOF

cat <<EOF >>.prettierrc.js
module.exports = {
  ...require('prettier-airbnb-config'),
  printWidth: 120,
};
EOF

cat <<EOF >>tsconfig.json
{
  "compilerOptions": {
    "forceConsistentCasingInFileNames": true,
    "outDir": "./dist",
    "rootDir": "./src"
  },
  "exclude": [
    "./node_modules"
  ]
}
EOF
