#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Usage: $0 <window_name>"
	exit 1
fi

window_name="$1"

if ! eww list-windows | grep -q "$window_name"; then
	echo "Window $window_name does not exist"
	exit 1
fi

if eww active-windows | grep -q "$window_name"; then
	eww close "$window_name"
else
	eww open "$window_name"
fi
