[[mgr.prepend_keymap]]
on = ["g", "d"]
run = "cd ~/dotfiles"
desc = "To dotfiles"

[[mgr.prepend_keymap]]
on = ["g", "D"]
run = "cd ~/Downloads"
desc = "To downloads"

[[input.prepend_keymap]]
on = ["<Esc>"]
run = "close"
desc = "Cancel input"

# [[manager.prepend_keymap]]
# on   = [ "l" ]
# run  = "plugin --sync smart-enter"
# desc = "Enter the child directory, or open the file"
#
# [[manager.prepend_keymap]]
# on   = [ "<Enter>" ]
# run  = "plugin --sync smart-enter"
# desc = "Enter the child directory, or open the file"
#
# [[manager.prepend_keymap]]
# on  = [ "T" ]
# run = "plugin --sync hide-preview"
#
# [[manager.prepend_keymap]]
# on  = [ "K" ]
# run = "plugin --sync parent-arrow --args=-1"
#
# [[manager.prepend_keymap]]
# on  = [ "J" ]
# run = "plugin --sync parent-arrow --args=1"

[[mgr.prepend_keymap]]
on = ["<C-s>"]
run = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"
